# Generated by Django 5.1.2 on 2024-10-27 09:48

import FurryFunniesApp.authors.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=40, validators=[FurryFunniesApp.authors.validators.LettersOnlyValidator()]),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=40, validators=[FurryFunniesApp.authors.validators.LettersOnlyValidator()]),
        ),
        migrations.AlterField(
            model_name='author',
            name='passcode',
            field=models.CharField(max_length=6, validators=[FurryFunniesApp.authors.validators.PasscodeValidator()]),
        ),
    ]
